mod code_block;
mod code_tabs;
mod comparison;
mod dogfood_banner;
mod feature_card;
mod features;
mod footer;
mod hero;
pub mod icons;
mod install;
mod unreleased_badge;
mod version_switcher;
mod walkthrough;

pub use code_block::CodeBlock;
pub use code_tabs::CodeTabs;
pub use comparison::Comparison;
pub use dogfood_banner::DogfoodBanner;
pub use feature_card::FeatureCard;
pub use features::Features;
pub use footer::Footer;
pub use hero::Hero;
pub use install::Install;
pub use unreleased_badge::UnreleasedBadge;
pub use version_switcher::VersionSwitcher;
pub use walkthrough::{ServeWalkthrough, Walkthrough};
